- name: Install duplicity
  apt:
    name: duplicity

- name: Create MySQL backup user
  mysql_user:
    name: "{{ backup_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:SELECT,LOCK TABLES"
    host: "localhost"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Create two necessary directories for backup
  file:
    path: '{{ item }}'
    recurse: yes
    state: directory
    mode: 0777
    owner: backup
  loop:
    - /home/backup/restore
    - /home/backup/mysql

- name: Copy MySQL configuration file
  template:
    src: backup.my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: 0700
  no_log: true

- name: Copy mysql cron
  template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
    owner: root
    group: root
    mode: 0744
