- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    
- name: Copy index page
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    follow: no
    
- name: Copy nginx configuration w/ prometheus ports
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  notify: Restart nginx
