- name: Download
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/

- name: Giving permission to influx_xporter
  file:
    path: /usr/local/bin/influx_stats_exporter_linux_amd64
    mode: 0755

- name: Create service
  template:
    src: influxdb_stats_exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    owner: prometheus
    group: prometheus
    mode: 0755
  notify:
    - Systemd reload
    - Restart prometheus-influxdb-stats-exporter
