- name: Install 'haproxy'
  apt:
    name: haproxy

- name: Copy haproxy.conf
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Ensure haproxy is started
  service:
    name: haproxy
    state: started
    enabled: yes
