- name: Add influx and telegraf key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key

- name: Add influx and telegraf repository into sources list
  apt_repository:
    repo: deb https://repos.influxdata.com/debian focal stable

- name: Install 'influxdb'
  apt:
    name: influxdb

- name: Ensure influxdb is running
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Install 'telegraf'
  apt:
    name: telegraf
    
- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
    
- name: Copy the influxdb config file and Restart influxdb
  copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify: Restart influxdb

- name: Copy the telegraf config file and Restart telegraf
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
