- name: Install Rsyslog
  apt:
    name: rsyslog
    state: latest

- name: Reconfigure Rsyslog
  template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart Rsyslog

- name: start rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes
