- name: Create two necessary directories for grafana
  file:
    path: '{{ item }}'
    recurse: yes
    state: directory
  loop:
    - /opt/grafana/provisioning/dashboards
    - /opt/grafana/provisioning/datasources

- name: Copy grafana.ini template
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: Restart docker grafana

- name: Copy datasource.yaml
  template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasource.yaml
  notify: Restart docker grafana

- name: Copy dashboard.yaml
  template:
    src: dashboard.yaml
    dest: /opt/grafana/provisioning/dashboards/dashboard.yaml

- name: Copy grafana dashboards
  copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - syslog
    - mysql
    - main
    - latency

- name: Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ reverse_proxy[1]['port'] }}:3000"
    volumes: /opt/grafana:/etc/grafana
    restart_policy: always
    container_default_behavior: no_defaults
