- name: "Install 'uwsgi'"
  ansible.builtin.apt:
    name: uwsgi

- name: "Install 'uwsgi-plugin-python3'"
  ansible.builtin.apt:
    name: uwsgi-plugin-python3
    state: latest
    
- name: "Copy config.ini file with owner and permissions"
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0644
  notify: Restart uwsgi
