- name: Install uwsgi
  apt:
    name: uwsgi

- name: Install 'uwsgi-plugin-python3'
  apt:
    name: uwsgi-plugin-python3
    state: latest

- name: Add uwsgi config file
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0644
  notify: Restart uwsgi

- name: Ensure that uwsgi is started
  service:
    name: uwsgi
    state: started
    enabled: yes  
