- name: Init
  hosts: db_servers, web_servers
  gather_facts: no
  become: yes
  roles:
    - init

- name: Collect info about all VMs
  hosts: all
  gather_facts: yes
  tasks:
    - setup:

- name: Bind9 DNS server
  hosts: dns_server
  gather_facts: no
  become: yes
  roles:
    - bind
    - bind_exporter

- name: Prometheus
  hosts: prometheus
  #gather_facts: no
  become: yes
  roles:
    - prometheus
  tags:
    - p

- name: Database server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_exporter

- name: Node
  hosts: all
  #gather_facts: no
  become: yes
  roles:
    - node_exporter



- name: Ansible webservers LAB2
  hosts: web_servers
  become: yes
  roles:
    - users
    - agama
    - uwsgi
    #- nginx

- name: nginx
  hosts: all
  become: yes
  roles:
    - nginx
    - nginx_exporter
  tags:
    - ng

- name: Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags:
   - g
