- name: "Add user 'agama'"
  ansible.builtin.user:
    name: agama
    
- name: "Create install directory 'opt/agama'"
  ansible.builtin.file:
    state: directory
    path: /opt/agama
    owner: agama
    mode: 0755
    
- name: "Install 'python3-flask-sqlalchemy'"
  ansible.builtin.apt:
    name: python3-flask-sqlalchemy
      
- name: "Install 'python3-pymysql'"
  ansible.builtin.apt:
    name: python3-pymysql

- name: "Download 'agama.py'"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: 0644
  
   
