- name: Creating  /opt/agama 
  file:
    path: /opt/agama
    state: directory
    
- name: Add the user agama
  user:
    name: agama
    system: yes
    state: present

- name: Download agama container from URL
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile
    
- name: Download agama.py
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: 0644

- name: Create agama docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      

- name: Agama Docker container
  community.docker.docker_container:
    name: "agama-{{item}}"
    image: agama
    restart_policy: always
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ agama_db }}.{{startup}}/{{ mysql_database }}
    published_ports: "{{ agama_container_prefix_port|string+item }}:8000"
  no_log: true
  with_sequence: 0-1
