- name: Add the user "backup" and generate keys
  user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Uploads /home/backup/.ssh/known_host
  template:
    dest: /home/backup/.ssh/known_hosts
    src: known_hosts.j2
    owner: root
    group: root
    mode: 0644
