- name: Add the user "backup" and generate keys
  user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- template:
    dest: /home/backup/.ssh/known_hosts
    src: known_hosts.j2
    owner: backup
    group: backup
    mode: 0777
