- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Restart nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: restarted
    enabled: yes
