- name: Install 'python3-mysql'
  apt:
    name: python3-pymysql

- name: Install 'mysql-server'
  apt:
    name: mysql-server
  notify: Restart mysql

- name: Copy the mysql config file and restart mysql server
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
    mode: 0644
  notify: Restart mysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user 
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  notify:
    - Reset MySQL source

- name: Create MySQL replication user
  mysql_user:
    name: "{{ replication }}"
    password: "{{ mysql_password }}"
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Make replication read only
  mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: Start mysql server
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  notify: 
    - Restart mysql 
