- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
  notify: Restart MySQL
  
- name: Override mysql configfile and restart
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
    mode: 0644
  notify: Restart MySQL
  
- name: Install 'python3-pymysql'
  ansible.builtin.apt:
    name: python3-pymysql
    
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Start mysql server
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
  become: yes
