- name: Restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: Restart mysqld exporter
  service:
    name:  prometheus-mysqld-exporter
    state: restarted


- name: zed
  community.mysql.mysql_query:
    login_db: "{{ mysql_user }}"
    query: "{{ item }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  loop:
    - stop slave;
    - reset slave;
    - start slave;
  when: inventory_hostname != mysql_host
