- name: Linux user juri
  ansible.builtin.user:
    name: juri

- name: Linux user roman
  ansible.builtin.user:
    name: roman

- name: Public key of linux user juri
  ansible.posix.authorized_key:
    user: juri
   # state: present
    key: https://github.com/hudolejev.keys

- name: Public key of linux user roman
  ansible.posix.authorized_key:
    user: roman
   # state: present
    key: https://github.com/romankuchin.keys
