- name: Add user pinger
  user:
    name: pinger


- name: Install 'fping'
  apt:
    name: fping

- name: Creates path
  file:
    path: "{{item}}"
    state: directory
    mode: 0777
  loop:
    - /etc/pinger

- name: Copy pinger.sh
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: pinger
    group: pinger
    mode: 0777
  loop:
    - src: pinger.sh
      dest: /usr/local/bin/pinger.sh
    - src: pinger.service
      dest: /etc/systemd/system/pinger.service

- name: Copy pinger.conf.j2 template into /etc/pinger/pinger.conf
  template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify:
    - Reload daemons
    - Restart pinger

- name: Ensure pinger is running
  service:
    name: pinger
    state: started
    enabled: true
