- name: Install 'prometheus-nginx-exporter'
  apt:
    name: prometheus-nginx-exporter
  notify: 
    - Restart nginx
    - Reload systemd
    - Restart nginx exporter

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Start nginx 
  service:
    name: nginx
    state: started

- name: Start nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
