- name: Install docker.io and python3-docker
  apt:
    name:
      - python3-docker
      - docker.io

- name: create folder
  file:
    path: /etc/docker
    state: directory

- name: copy dns
  template:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"

- name: Ensure docker is running
  service:
    name: docker
    state: started
    enabled: true
