- name: Restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: Reset MySQL source
  mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ replication }}"
    primary_password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host

- name: zed
  community.mysql.mysql_query:
    login_db: "{{ mysql_user }}"
    query: "{{ item }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  loop:
    - stop slave;
    - reset slave;
    - start slave;
  when: inventory_hostname != mysql_host
