- name: server print
  debug:
    msg:
      - "{{hostvars['pongraczfarkas-2']}}"


- name: Install 'bind9'
  apt:
    name: bind9

- name: Ensure bind9 is running
  ansible.builtin.service:
    name: bind9
    state: started


- template:
    dest: /etc/bind/named.conf.options
    src: named.conf.options.j2
  notify: Restart bind9

- template:
    dest: /etc/bind/named.conf.local
    src: named.conf.local.j2
  notify: Restart bind9

- template:
    dest: /var/lib/bind/{{startup}}
    src: db.worldismine
  notify: rndc reload



- name: Stop service systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no
