- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    
- name: Ensure bind9 is running
  ansible.builtin.service:
    name: bind9
    state: started
    
- name: Update named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9
  
- name: Upload db.worldismine
  ansible.builtin.template:
    src: db.worldismine
    dest: /var/cache/bind/{{ startup }}
    
- name: Upload named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9
  
- name: Update resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  notify: rndc reload
  
- name: Stop systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: no
  
