- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: hostname
  hostname: 
    name: "{{ inventory_hostname }}"

#- name: what is inventory_hostname
 # debug: var=inventory_hostname